version: '3.8'

services:
  do360now_agent_x:
    image: do360now/do360now_agent_x:0.1.0
    container_name: do360now-agent-x
    restart: unless-stopped


  medicalnetworks_agent_x:
    image: do360now/medicalnetworks_agent_x:0.1.0
    container_name: medicalnetworks-agent-x
    depends_on:
      - do360now_agent_x
    restart: unless-stopped
    entrypoint: ["sh", "-c", "sleep 300 && python chatgpt_agent_x.py"]


  machadoclement_agent_x:
    image: do360now/machadoclement_agent_x:0.1.0
    container_name: machadoclement-agent-x
    depends_on:
      - medicalnetworks_agent_x
    restart: unless-stopped
    entrypoint: ["sh", "-c", "sleep 300 && python chatgpt_agent_x.py"]

