version: '3.8'
services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env  # This will load environment variables from your .env file
    depends_on:
      - sql-server
    networks:
      - app-network

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      SA_PASSWORD: "IyJmXF52C11CJk1OEzc1va"  # Referencing the password from the .env file
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - ./init-sql-script.sql:/docker-entrypoint-initdb.d/init-sql-script.sql  # Add this line

networks:
  app-network:
    driver: bridge
