#!/usr/bin/env python3
"""
add_article.py — Validate and insert a finished article into HelloAi.

Article PROSE is generated by the Claude Code article-writer agent (see
.claude/agents/article-writer.md). This script only validates the finished
JSON and inserts it deterministically into data/articles.json.

Usage:
  python scripts/add_article.py --file article.json
  echo '{...}' | python scripts/add_article.py
  python scripts/add_article.py --file article.json --dry-run

Input JSON schema (all fields except title/excerpt/category/content are optional):
  {
    "title":    "Article title (required)",
    "excerpt":  "Short hook for article card (required)",
    "category": "One of: Analysis, Opinion, Discovery, Review, Tutorial (required)",
    "content":  ["paragraph 1", "paragraph 2", ...] (required, non-empty list),
    "slug":     "url-slug"       (optional, default = slugify(title)),
    "date":     "YYYY-MM-DD"     (optional, default = today),
    "readTime": "N min"          (optional, default = estimated from content)
  }
"""

import argparse
import json
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from config import config
from utils import (
    setup_logger,
    read_json,
    write_json,
    today_iso,
    slugify,
)

log = setup_logger("add-article")

VALID_CATEGORIES = {"Analysis", "Opinion", "Discovery", "Review", "Tutorial"}
MIN_PARAGRAPH_CHARS = 40


# ─── Helpers ────────────────────────────────────────────────────────────────

def estimate_read_time(content: list[str]) -> str:
    """Estimate read time from paragraph list."""
    word_count = sum(len(p.split()) for p in content)
    minutes = max(1, math.ceil(word_count / 250))
    return f"{minutes} min"


def validate_input(data: dict) -> list[str]:
    """Validate the incoming article JSON. Returns list of error strings."""
    errors = []

    for field in ("title", "excerpt", "category", "content"):
        if field not in data:
            errors.append(f"Missing required field: '{field}'")

    if errors:
        return errors  # stop early — remaining checks need the fields present

    if not isinstance(data["content"], list) or len(data["content"]) == 0:
        errors.append("'content' must be a non-empty list of strings")
    else:
        short = [
            i for i, p in enumerate(data["content"])
            if not isinstance(p, str) or len(p) < MIN_PARAGRAPH_CHARS
        ]
        if short:
            errors.append(
                f"Paragraphs at index(es) {short} are not strings or are shorter "
                f"than {MIN_PARAGRAPH_CHARS} chars"
            )

    if data.get("category") not in VALID_CATEGORIES:
        errors.append(
            f"'category' must be one of {sorted(VALID_CATEGORIES)}, "
            f"got: {data.get('category')!r}"
        )

    return errors


def build_article_entry(data: dict) -> dict:
    """Build a complete article entry for articles.json from validated input."""
    content = data["content"]
    return {
        "slug": data.get("slug") or slugify(data["title"]),
        "title": data["title"],
        "excerpt": data["excerpt"],
        "date": data.get("date") or today_iso(),
        "category": data["category"],
        "readTime": data.get("readTime") or estimate_read_time(content),
        "content": content,
    }


def add_article(article: dict, dry_run: bool = False) -> None:
    """Add article to articles.json (prepend, trim to max)."""
    articles = read_json(config.articles_path)

    # Dup-slug guard with date suffix
    existing_slugs = {a["slug"] for a in articles}
    if article["slug"] in existing_slugs:
        log.warning(f"Slug '{article['slug']}' already exists. Appending date suffix.")
        article["slug"] += f"-{today_iso()}"

    # Prepend (newest first)
    articles.insert(0, article)

    # Trim to max
    if len(articles) > config.max_articles:
        removed = articles[config.max_articles:]
        articles = articles[:config.max_articles]
        for r in removed:
            log.info(f"  Trimmed old article: '{r['title']}'")

    if dry_run:
        log.info("[DRY RUN] Would write article:")
        log.info(f"  Title:      {article['title']}")
        log.info(f"  Slug:       {article['slug']}")
        log.info(f"  Category:   {article['category']}")
        log.info(f"  Date:       {article['date']}")
        log.info(f"  Read time:  {article['readTime']}")
        log.info(f"  Paragraphs: {len(article['content'])}")
        print("\n--- PREVIEW ---")
        print(f"\n# {article['title']}\n")
        print(f"*{article['excerpt']}*\n")
        for p in article["content"]:
            print(f"{p}\n")
    else:
        write_json(config.articles_path, articles)
        log.info(f"Article added: '{article['title']}'")

        # Update site timestamp
        site = read_json(config.site_path)
        site["lastUpdated"] = today_iso()
        write_json(config.site_path, site)
        log.info("Updated site.json timestamp")


# ─── CLI ────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Validate and insert a finished article JSON into data/articles.json. "
            "Article prose must be produced by the article-writer agent beforehand."
        )
    )
    parser.add_argument(
        "--file",
        type=Path,
        help="Path to article JSON file (default: read from stdin)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview the article without writing to file",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    log.info("=" * 50)
    log.info("HelloAi Article Inserter")
    log.info("=" * 50)

    # Read JSON
    try:
        if args.file:
            raw = args.file.read_text(encoding="utf-8")
        else:
            raw = sys.stdin.read()
        data = json.loads(raw)
    except (OSError, json.JSONDecodeError) as e:
        log.error(f"Failed to read/parse input JSON: {e}")
        sys.exit(1)

    # Validate
    errors = validate_input(data)
    if errors:
        for err in errors:
            log.error(f"Validation error: {err}")
        sys.exit(1)

    # Build entry
    article = build_article_entry(data)

    # Insert
    add_article(article, dry_run=args.dry_run)

    if not args.dry_run:
        log.info("Run `npx jest` to validate, then commit and deploy.")


if __name__ == "__main__":
    main()
