apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-restore
  namespace: <your-namespace>
spec:
  template:
    spec:
      containers:
        - name: mongodb-restore
          image: mongo:latest
          command: ["/bin/sh", "-c"]
          args:
            - >
              mongorestore --gzip --archive=/backup/mongodb-<date>.gz --uri="mongodb://<username>:<password>@<mongodb-service>:<port>/<database>"
          volumeMounts:
            - name: backup-storage
              mountPath: /backup
      restartPolicy: OnFailure
      volumes:
        - name: backup-storage
          persistentVolumeClaim:
            claimName: mongodb-backup-pvc
